name: ubuntu18.04

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: fetch google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.10.0.zip
      - name: check GCC versions
        run: |
          echo `gcc --version`
          echo `g++ --version`
          echo ${CC}
          echo ${CXX}
      - name: prepare install dir
        run: mkdir lib/
      - name: install google test
        run: |
          unzip release-1.10.0.zip
          mkdir googletest-release-1.10.0/build && cd googletest-release-1.10.0/build
          cmake -DCMAKE_INSTALL_PREFIX=../../lib/ ../ && make -j4
          make install
      - name: build
        run: |
          mkdir build && cd build
          cmake ../
          make -j4
      - name: test
        run: |
          ./build/test_socknet/test_socknet
